[package]
name = "AxonScript"
version = "0.0.1"
edition = "2024"

build = "build.rs"

[dependencies]
llvm-sys =  "201.0.1"
logos = "0.15.0"
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.17"
console = "0.15"
libc = "0.2"
target-lexicon = "0.13.2"
[build-dependencies]
cc = "1"
